# Generated by Django 2.0.3 on 2018-03-20 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('uuid', models.IntegerField(primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=500)),
                ('finger_print', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Fingerprint_device',
            fields=[
                ('location', models.CharField(max_length=100)),
                ('fid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('money', models.IntegerField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biometric_ticket.Customer')),
            ],
        ),
    ]
