# Generated by Django 2.0.3 on 2018-03-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric_ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LED_bulb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
            ],
        ),
    ]
