# Generated by Django 2.0.3 on 2018-03-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biometric_ticket', '0003_led_bulb_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='led_bulb',
            name='name',
        ),
    ]
