# Generated by Django 2.0.3 on 2018-03-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric_ticket', '0004_remove_led_bulb_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mappingstation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_station_name', models.CharField(max_length=20)),
                ('ghatkopar', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='cust_id',
            new_name='uuid',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
