# Generated by Django 2.0.3 on 2018-03-27 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biometric_ticket', '0005_auto_20180327_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('fare', models.IntegerField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=20)),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biometric_ticket.Customer')),
            ],
        ),
    ]
